#!/usr/bin/env bash

# Theme switcher script
# Applies selected theme to Hyprland, Waybar, and Rofi

THEME_DIR="$HOME/.config/hypr/themes"
THEME_FILE="$THEME_DIR/theme-definitions.json"
CURRENT_THEME_FILE="$HOME/.cache/current-theme"
ROFI_THEME="$HOME/.config/rofi/control-center.rasi"

# Create cache directory
mkdir -p "$(dirname "$CURRENT_THEME_FILE")"

# Check if theme file exists
if [ ! -f "$THEME_FILE" ]; then
    notify-send "Theme Switcher" "Theme definitions file not found" -u critical
    exit 1
fi

# Get list of themes
themes=$(jq -r '.themes | keys[]' "$THEME_FILE" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')

# Add pywal option at the top
#themes="🎨 Pywal (Wallpaper)
#$themes"

# Show theme selection menu
selected=$(echo "$themes" | rofi -dmenu -i -p "Select Theme" -theme "$ROFI_THEME")

if [ -z "$selected" ]; then
    exit 0
fi

# Check if pywal was selected
if [[ "$selected" == *"Pywal"* ]]; then
    ~/.config/hypr/scripts/pywal-theme.sh
    exit 0
fi

# Convert selected theme name back to key format
theme_key=$(echo "$selected" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

# Get theme colors from JSON
bg=$(jq -r ".themes.\"$theme_key\".colors.bg" "$THEME_FILE")
bg_alt=$(jq -r ".themes.\"$theme_key\".colors.\"bg-alt\"" "$THEME_FILE")
fg=$(jq -r ".themes.\"$theme_key\".colors.fg" "$THEME_FILE")
fg_alt=$(jq -r ".themes.\"$theme_key\".colors.\"fg-alt\"" "$THEME_FILE")
accent=$(jq -r ".themes.\"$theme_key\".colors.accent" "$THEME_FILE")
accent_alt=$(jq -r ".themes.\"$theme_key\".colors.\"accent-alt\"" "$THEME_FILE")
urgent=$(jq -r ".themes.\"$theme_key\".colors.urgent" "$THEME_FILE")
warning=$(jq -r ".themes.\"$theme_key\".colors.warning" "$THEME_FILE")
success=$(jq -r ".themes.\"$theme_key\".colors.success" "$THEME_FILE")
border_active=$(jq -r ".themes.\"$theme_key\".colors.\"border-active\"" "$THEME_FILE")
border_inactive=$(jq -r ".themes.\"$theme_key\".colors.\"border-inactive\"" "$THEME_FILE")

# Convert hex to rgba format for Hyprland
hex_to_rgba() {
    hex=$1
    hex=${hex#\#}
    echo "rgba(${hex}ff)"
}

# Update Hyprland theme.conf
cat > "$HOME/.config/hypr/theme.conf" << EOF
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                            Theme Configuration                               ║
# ║              Auto-generated by theme switcher - DO NOT EDIT                 ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# Current theme: $selected

# Border colors
general {
    col.active_border = $(hex_to_rgba "$border_active") $(hex_to_rgba "$accent_alt") 45deg
    col.inactive_border = $(hex_to_rgba "$border_inactive")
}

# Group border colors
group {
    col.border_active = $(hex_to_rgba "$border_active")
    col.border_inactive = $(hex_to_rgba "$border_inactive")
}
EOF

# Update Waybar CSS colors
sed -i "s/@define-color bg .*;/@define-color bg $bg;/" "$HOME/.config/waybar/style.css"
sed -i "s/@define-color fg .*;/@define-color fg $fg;/" "$HOME/.config/waybar/style.css"
sed -i "s/@define-color accent .*;/@define-color accent $accent;/" "$HOME/.config/waybar/style.css"
sed -i "s/@define-color urgent .*;/@define-color urgent $urgent;/" "$HOME/.config/waybar/style.css"
sed -i "s/@define-color warning .*;/@define-color warning $warning;/" "$HOME/.config/waybar/style.css"
sed -i "s/@define-color success .*;/@define-color success $success;/" "$HOME/.config/waybar/style.css"

# Update Dunst notification colors
if [ -f "$HOME/.config/dunst/dunstrc" ]; then
    sed -i "/^\[urgency_low\]/,/^\[/ { s/background = .*/background = \"$bg\"/; s/foreground = .*/foreground = \"$fg\"/; s/frame_color = .*/frame_color = \"$accent\"/; }" "$HOME/.config/dunst/dunstrc"
    sed -i "/^\[urgency_normal\]/,/^\[/ { s/background = .*/background = \"$bg\"/; s/foreground = .*/foreground = \"$fg\"/; s/frame_color = .*/frame_color = \"$accent\"/; }" "$HOME/.config/dunst/dunstrc"
    sed -i "/^\[urgency_critical\]/,/^\$/ { s/background = .*/background = \"$bg\"/; s/foreground = .*/foreground = \"$fg\"/; s/frame_color = .*/frame_color = \"$urgent\"/; }" "$HOME/.config/dunst/dunstrc"
    
    # Reload dunst
    killall dunst 2>/dev/null
    dunst &
fi

# Update all Rofi themes
for rofi_file in ~/.config/rofi/*.rasi; do
    sed -i "s/bg: #.*;/bg: $bg;/" "$rofi_file"
    sed -i "s/bg-alt: #.*;/bg-alt: $bg_alt;/" "$rofi_file"
    sed -i "s/fg: #.*;/fg: $fg;/" "$rofi_file"
    sed -i "s/fg-alt: #.*;/fg-alt: $fg_alt;/" "$rofi_file" 2>/dev/null 
    sed -i "s/accent: #.*;/accent: $accent;/" "$rofi_file"
    sed -i "s/urgent: #.*;/urgent: $urgent;/" "$rofi_file"
done

# Update Kitty terminal colors
if [ -f "$HOME/.config/kitty/kitty.conf" ]; then
    sed -i "s/^background #.*/background $bg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^foreground #.*/foreground $fg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^cursor #.*/cursor $fg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^cursor_text_color #.*/cursor_text_color $bg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^selection_background #.*/selection_background $bg_alt/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^selection_foreground #.*/selection_foreground $fg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^active_tab_background #.*/active_tab_background $accent/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^active_tab_foreground #.*/active_tab_foreground $bg/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^inactive_tab_background #.*/inactive_tab_background $bg_alt/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^inactive_tab_foreground #.*/inactive_tab_foreground $fg_alt/" "$HOME/.config/kitty/kitty.conf"
    sed -i "s/^tab_bar_background #.*/tab_bar_background $bg/" "$HOME/.config/kitty/kitty.conf"
    
    # Reload Kitty configuration for all instances
    killall -SIGUSR1 kitty 2>/dev/null
fi

# Save current theme
echo "$theme_key" > "$CURRENT_THEME_FILE"

# Reload Hyprland configuration
hyprctl reload

# Restart Waybar
killall waybar
waybar &

# Restart Portals to ensure stability
~/.config/hypr/scripts/xdg-portal.sh &

# Notify user
notify-send "Theme Switcher" "Applied theme: $selected"
